### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_id'

### ISSUE THREAD

**Issue by pivcheg** [sha256-enjoyer/simple-telegram-bot#1]
Приветствую.
После запуска бота и отправки любого сообщения в группу куда добавлен бот, появляется ошибка:
```
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/bot/.local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/bot/.local/lib/python3.9/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/home/bot/rent_bot/main.py", line 55, in messages_exchange
    reply_id = int(update.message.reply_to_message.message_id)
AttributeError: 'NoneType' object has no attribute 'message_id'
```

Вот кусок кода из функции **messages_exchange**, где происходит ошибка:
```
    if chat_id < 0:
        reply_id = int(update.message.reply_to_message.message_id)
        if str(reply_id) in SETTINGS['messages']:
            context.bot.copy_message(SETTINGS['messages'][str(reply_id)], chat_id, int(update.message.message_id))
            logging.debug(f'message_repost: reply from {chat_id} for {SETTINGS["messages"][str(reply_id)]}, message {update.message.message_id}')
```

**Comment by sha256-enjoyer** [comment]
Обновил репозиторий
Проверьте также, что вы устанавливаете **default_channel** в .env
Посмотреть id канала можно при попытке добавить его через **/add**
